// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCggJg_HwqRGHl68xEzEN1sQj75JzEDwzM',
    appId: '1:622622828609:web:9f99358f6f00f75dbebec0',
    messagingSenderId: '622622828609',
    projectId: 'tennis-shop-69dc6',
    authDomain: 'tennis-shop-69dc6.firebaseapp.com',
    storageBucket: 'tennis-shop-69dc6.appspot.com',
    measurementId: 'G-G9VKR0PSVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDX9FSbq4VJhJx6CYwy4WhH4Q1ZX0tAw',
    appId: '1:622622828609:android:33a6558ff8313da8bebec0',
    messagingSenderId: '622622828609',
    projectId: 'tennis-shop-69dc6',
    storageBucket: 'tennis-shop-69dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApoNqrJQFMauQO6FX3AojEXBK3JFgPZUM',
    appId: '1:622622828609:ios:6845810034db7d7ebebec0',
    messagingSenderId: '622622828609',
    projectId: 'tennis-shop-69dc6',
    storageBucket: 'tennis-shop-69dc6.appspot.com',
    iosBundleId: 'com.example.tennisStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApoNqrJQFMauQO6FX3AojEXBK3JFgPZUM',
    appId: '1:622622828609:ios:6845810034db7d7ebebec0',
    messagingSenderId: '622622828609',
    projectId: 'tennis-shop-69dc6',
    storageBucket: 'tennis-shop-69dc6.appspot.com',
    iosBundleId: 'com.example.tennisStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCggJg_HwqRGHl68xEzEN1sQj75JzEDwzM',
    appId: '1:622622828609:web:1833ee9ed96cb8a7bebec0',
    messagingSenderId: '622622828609',
    projectId: 'tennis-shop-69dc6',
    authDomain: 'tennis-shop-69dc6.firebaseapp.com',
    storageBucket: 'tennis-shop-69dc6.appspot.com',
    measurementId: 'G-SFV0KJQDJM',
  );
}
